FROM python:3.13

WORKDIR /app

COPY FastAPI/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY FastAPI ./src
EXPOSE 8000

RUN useradd fastapiuser

USER fastapiuser

CMD ["fastapi", "dev", "src/main.py", "--host", "0.0.0.0"]
